# -*- coding: utf-8 -*-
"""Untitled

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12kKOhdCDi5M7-zFLUDupkiU48ARmxdZ4
"""

pip install matplotlib numpy

import numpy as np
import matplotlib.pyplot as plt
from matplotlib.animation import FuncAnimation
from matplotlib.patches import Rectangle
from IPython.display import HTML

# ---------- parameters ----------
A = 0.35                 # amplitude (axis units)
f = 0.30                 # frequency (Hz)
omega = 2*np.pi*f
T_end = 10               # seconds
fps = 30
frames = T_end * fps

t = np.linspace(0, T_end, frames)
x = A * np.cos(omega * t)  # SHM displacement

# scene layout (axis coordinates)
wall_x = -1.2
eq_x = -0.2               # equilibrium position of mass center
y0 = 0.0

# ---------- figure ----------
fig, ax = plt.subplots(figsize=(9, 3.5))
ax.set_xlim(-1.5, 1.5)
ax.set_ylim(-0.6, 0.6)
ax.axis("off")

# gray background
fig.patch.set_facecolor((0.75, 0.75, 0.75))
ax.set_facecolor((0.75, 0.75, 0.75))

# wall
ax.plot([wall_x, wall_x], [-0.35, 0.35], color="white", linewidth=4)

# mass (blue block)
mass_w, mass_h = 0.18, 0.18
mass = Rectangle((0, 0), mass_w, mass_h, color="blue")
ax.add_patch(mass)

# spring line (polyline)
spring_line, = ax.plot([], [], color="white", linewidth=2)

def spring_points(x1, x2, y, coils=22, amp=0.08):
    xs = np.linspace(x1, x2, coils+1)
    ys = np.full_like(xs, y)
    for i in range(1, coils):
        ys[i] = y + (amp if i % 2 else -amp)
    ys[0] = y
    ys[-1] = y
    return xs, ys

def init():
    spring_line.set_data([], [])
    mass.set_xy((eq_x - mass_w/2, y0 - mass_h/2))
    return spring_line, mass

def update(i):   # <-- IMPORTANT: must be update(i):
    mx = eq_x + x[i]
    mass.set_xy((mx - mass_w/2, y0 - mass_h/2))

    left_face = mx - mass_w/2
    xs, ys = spring_points(wall_x, left_face, y0, coils=22, amp=0.08)
    spring_line.set_data(xs, ys)

    return spring_line, mass

ani = FuncAnimation(fig, update, frames=frames, init_func=init, interval=1000/fps, blit=True)
HTML(ani.to_jshtml())